# Cloudflare Pages — KV: art-caffe-MENU_KV
name = "art-caffe"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "MENU_KV"
id = "5cd5c70f235d407086ac8ef38432a892"
preview_id = "5cd5c70f235d407086ac8ef38432a892"
